# Jekyll technical configuration!
#

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
github: metadata

minimal_mistakes_skin    : "default" 

# Site Settings
locale          : "en"
title           : "Status and Statistics of arc42 Sites"
title_separator : "-"
name            : ""
description     : ""
url             : "https://status.arc42.org" # the base hostname & protocol for your site
baseurl         : ""  # the subpath of your site, e.g. "/blog"
repository      : "arc42/status.arc42.org-site" # GitHub username/repo-name
teaser          :  # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs     : false # true, false (default)
words_per_minute : 200
permalink       : none

# Social Sharing
  # For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Organization # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false

# Site Author
author:
  name             : "Dr. Gernot Starke"
  location         : "Cologne"
  email            : gernotstarke@mailbox.org

# Reading Files
include:
  - _pages
  - images
  - images/badges
  - assets
  
exclude:
  - Dockerfile
  - docker-compose*
  - .asset-cache
  - docs/
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - _manage-site.sh
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - README.md
  - tmp
 
keep_files:
  - sitemap.xml
  - robots.txt

  
encoding: "utf-8"
markdown_ext: "markdown,md"

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

# Conversion
markdown: kramdown
highlighter: 
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: 


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate:  # amount of posts to show
paginate_path: #/page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-include-cache
  


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-include-cache
  


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
