@startuml
'https://plantuml.com/sequence-diagram

autonumber


group parallel [domain.go]
    domain -> domain : init logger
    loop Arc42Sites
      par LoadStats4Sites
        domain -> siteStats
        activate siteStats
        par getSiteStatistics
            siteStats -> plausible: get 7D
            siteStats -> plausible: get 30D
            siteStats -> plausible: get 12M
        end
        deactivate siteStats
        domain -> repoStats
        par getRepoStatistics
            repoStats -> github
        end
        domain -> github: getRepoStatistics

    end

end
@enduml