:jbake-title: Introduction and Goals
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: arc42
:jbake-order: 1
:filename: /chapters/01_introduction_and_goals.adoc
ifndef::imagesdir[:imagesdir: ../../images]

:toc:



[[section-introduction-and-goals]]
== Introduction and Goals



=== Requirements Overview

[glossary]
F-001:: publish current usage statistics of arc42 websites

F-002:: publish current repository statistics (like issues, bugs) of arc42 websites

F-003:: store important results and events persistently for future reference

F-004:: inform owners of important system events

=== Quality Goals

[glossary]

Q-001:: Accurate: Site usage (like pageviews, visitor counts) results have to be correct. Spam- and bot traffic shall be excluded from counts. Error rates in data representation should be below 0.5% as measured by data quality checks.

Q-002:: Understandable: At least 90% of users should be able to understand the displayed data without further instruction, as measured by a user survey.

Q-003:: Environmental friendly: Reduce computing resources used as much as possible.

Q-004:: Reliable: The system achieves a minimum uptime of 99.9% per month. System recovery from any single point of failure should not exceed 5 minutes. Error rates (including server errors, network timeouts, and data access issues) should not exceed 0.1% of all system transactions.

Q-005:: Available: statics are available via the website 24x7. Short periods (hours) of downtime can be allowed, in such cases cached or dated results shall be displayed.

Q-006:: Collection of statistics shall be compliant with European data privacy regulations as much as possible. It shall not use cookies. It shall not track personal user information (except browser and device type plus user geolocation)

=== Stakeholders



[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
